### ISSUE TITLE
"You do not have the SUPER privilege and binary logging is enabled"

### ISSUE THREAD

**Issue by thbar** [soundcloud/lhm#76] opened 2014-10-20 14:22 UTC
Hello,

we migrated from a RDS-backed MySQL 5.5 to a newer generation RDS MySQL 5.6, and the first attempt to add an index using lhm gives us this error:

```
I, [2014-10-20T13:56:11.100569 #8934]  INFO -- : Starting LHM run on table=lhmn_pushes
I, [2014-10-20T13:56:11.102629 #8934]  INFO -- : Starting run of class=Lhm::Migrator
I, [2014-10-20T13:56:11.344552 #8934]  INFO -- : Starting run of class=Lhm::Entangler
E, [2014-10-20T13:56:11.350324 #8934] ERROR -- : Error in class=Lhm::Entangler, reverting. exception=ActiveRecord::StatementInvalid message=Mysql2::Error: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable): create trigger `lhmt_del_pushes`
after delete on `pushes` for each row
delete ignore from `lhmn_pushes` /* large hadron migration */
where `lhmn_pushes`.`id` = OLD.`id` /* large hadron migration */
rake aborted!
An error has occurred, all later migrations canceled:

Mysql2::Error: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable): drop trigger if exists `lhmt_del_pushes` /* large hadron migration */
```

After discussing this with my client's sysadmin, SUPER cannot be used on RDS apparently, and binary logging is always on for point in time recovery.

This is also the first time we use LHM to add an index (previously it was just for columns).

Is the error message reliable here?

Did anyone meet this issue and can it be solved?

thanks!

**Comment by arthurnn** [comment] 2015-03-14 23:52
will close this one, as I can say it is a duplicate of https://github.com/soundcloud/lhm/issues/65

**Closed by arthurnn** 2015-03-14 23:52 UTC

**Comment by mnpenner** [comment] 2015-05-30 22:06
For others that are stumbling across this issue via google, run this:

    mysql -u USERNAME -p
    set global log_bin_trust_function_creators=1;

**Comment by nickdowse** [comment] 2016-04-26 09:38
To follow up on @mnpenner's comment: When using RDS you have to create a new RDS parameter group (this can be done from the RDS dashboard on the web), set `log_bin_trust_function_creators` to 1 (as opposed to `<engine-default>`, save the parameter group.

Then modify your RDS instance to use this parameter group, save, and reboot your RDS instance and it should work.

**Comment by ka4a** [comment] 2017-12-11 07:34
sed -ie "s/DEFINER=\`a-z0-9A-Z*\`@\`a-z0-9A-Z*\`/DEFINER=CURRENT_USER /g sqldump.sql

This help me with my backup file. succesful import.

**Comment by leobut** [comment] 2019-07-03 14:00
If you are facing this issue and your database is on **Google Cloud**, follow this guide to set the `log_bin_trust_function_creators` flag of your database to `true`: https://cloud.google.com/sql/docs/mysql/flags

**Comment by Mohamed-Nusry** [comment] 2021-01-19 06:02
So you have to add [SET GLOBAL log_bin_trust_function_creators = 1;
](https://nsrtechx.com/mysql-you-do-not-have-the-super-privilege-issue-fix/)

**Comment by gioudi** [comment] 2022-05-22 15:41
Command [SET GLOBAL log_bin_trust_function_creators = 1;] is not working for me:  Access denied; you need (at least one of) the SUPER or SYSTEM_VARIABLES_ADMIN privilege(s) for this operation

**Comment by alxestevam** [comment] 2022-06-08 18:14
> Command [SET GLOBAL log_bin_trust_function_creators = 1;] is not working for me: Access denied; you need (at least one of) the SUPER or SYSTEM_VARIABLES_ADMIN privilege(s) for this operation

You can go to the Console UI, edit the sql instance and add the flag log_bin_trust_function_creators with value "on"

**Comment by oh-andres-zepeda** [comment] 2022-06-24 04:12
If using AWS RDS, this error can be bypassed by following these instructions from amazon [https://aws.amazon.com/premiumsupport/knowledge-center/rds-mysql-functions/](url)

**Comment by rushiikesh** [comment] 2023-11-04 14:15
> I finally understood: the latest gen of RDS MySQL has triggers disabled (while our first gen apparently had it enabled).
> 
> The fix seems to be to [set log_bin_trust_function_creators to 1 indeed](http://techtavern.wordpress.com/2013/06/17/mysql-triggers-and-amazon-rds/).

really help me thanks alot
